name: Announce LTS RCs

on:
  release:
    types: [prereleased]

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Post on Discourse
        uses: roots/discourse-topic-github-release-action@fc9e50fa1a1ce6255ba4d03f104382845b79ad5f # v1.0.0
        with:
          discourse-api-key: ${{ secrets.DISCOURSE_RELEASES_API_KEY }}
          discourse-base-url: https://community.jenkins.io/
          discourse-author-username: jenkins-release-bot
          discourse-category: 23
      - name: Post on mailing list
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          secure: true
          subject: ${{ github.event.release.tag_name }} has been released
          to: jenkinsci-dev@googlegroups.com
          from: Jenkins Release Bot
          html_body: ${{ github.event.release.body }}
          convert_markdown: true
